package com.jplus.dao;

import com.jplus.model.LiuYan;
import java.util.List;

public interface LiuYanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_liuyan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_liuyan
     *
     * @mbggenerated
     */
    int insert(LiuYan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_liuyan
     *
     * @mbggenerated
     */
    LiuYan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_liuyan
     *
     * @mbggenerated
     */
    List<LiuYan> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_liuyan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LiuYan record);
}