package com.jplus.model;

import java.io.Serializable;

/**
 * 此类由MySQLToModel工具自动生成 
 * 备注(数据表的comment字段)：无备注信息
 * 
 * @author Chitry
 * @title 论坛版块推荐信息实体
 * @since 2015-07-22 19:52:51
 */
public class BBSRecommend implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_bbsrecommend.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_bbsrecommend.br_name
     *
     * @mbggenerated
     */
    private String brName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_bbsrecommend.br_title
     *
     * @mbggenerated
     */
    private String brTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_bbsrecommend.br_url
     *
     * @mbggenerated
     */
    private String brUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_bbsrecommend.br_purl
     *
     * @mbggenerated
     */
    private String brPurl;
    private String brPurl2;
    
    

    public String getBrPurl2() {
		return brPurl2;
	}

	public void setBrPurl2(String brPurl2) {
		this.brPurl2 = brPurl2;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_bbsrecommend.br_descriptions
     *
     * @mbggenerated
     */
    private String brDescriptions;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_bbsrecommend.id
     *
     * @return the value of j_bbsrecommend.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_bbsrecommend.id
     *
     * @param id the value for j_bbsrecommend.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_bbsrecommend.br_name
     *
     * @return the value of j_bbsrecommend.br_name
     *
     * @mbggenerated
     */
    public String getBrName() {
        return brName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_bbsrecommend.br_name
     *
     * @param brName the value for j_bbsrecommend.br_name
     *
     * @mbggenerated
     */
    public void setBrName(String brName) {
        this.brName = brName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_bbsrecommend.br_title
     *
     * @return the value of j_bbsrecommend.br_title
     *
     * @mbggenerated
     */
    public String getBrTitle() {
        return brTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_bbsrecommend.br_title
     *
     * @param brTitle the value for j_bbsrecommend.br_title
     *
     * @mbggenerated
     */
    public void setBrTitle(String brTitle) {
        this.brTitle = brTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_bbsrecommend.br_url
     *
     * @return the value of j_bbsrecommend.br_url
     *
     * @mbggenerated
     */
    public String getBrUrl() {
        return brUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_bbsrecommend.br_url
     *
     * @param brUrl the value for j_bbsrecommend.br_url
     *
     * @mbggenerated
     */
    public void setBrUrl(String brUrl) {
        this.brUrl = brUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_bbsrecommend.br_purl
     *
     * @return the value of j_bbsrecommend.br_purl
     *
     * @mbggenerated
     */
    public String getBrPurl() {
        return brPurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_bbsrecommend.br_purl
     *
     * @param brPurl the value for j_bbsrecommend.br_purl
     *
     * @mbggenerated
     */
    public void setBrPurl(String brPurl) {
        this.brPurl = brPurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_bbsrecommend.br_descriptions
     *
     * @return the value of j_bbsrecommend.br_descriptions
     *
     * @mbggenerated
     */
    public String getBrDescriptions() {
        return brDescriptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_bbsrecommend.br_descriptions
     *
     * @param brDescriptions the value for j_bbsrecommend.br_descriptions
     *
     * @mbggenerated
     */
    public void setBrDescriptions(String brDescriptions) {
        this.brDescriptions = brDescriptions;
    }
}