package com.jplus.model;

import java.io.Serializable;

/**
 * 此类由MySQLToModel工具自动生成 
 * 备注(数据表的comment字段)：无备注信息
 * 
 * @author Chitry
 * @title 认证信息实体
 * @since 2015-07-22 19:52:51
 */
public class Identify implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_identify.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_identify.iname
     *
     * @mbggenerated
     */
    private String iname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_identify.certnum
     *
     * @mbggenerated
     */
    private String certnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_identify.sessions
     *
     * @mbggenerated
     */
    private Integer sessions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_identify.positions
     *
     * @mbggenerated
     */
    private String positions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_identify.descriptions
     *
     * @mbggenerated
     */
    private String descriptions;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_identify.id
     *
     * @return the value of j_identify.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_identify.id
     *
     * @param id the value for j_identify.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_identify.iname
     *
     * @return the value of j_identify.iname
     *
     * @mbggenerated
     */
    public String getIname() {
        return iname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_identify.iname
     *
     * @param iname the value for j_identify.iname
     *
     * @mbggenerated
     */
    public void setIname(String iname) {
        this.iname = iname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_identify.certnum
     *
     * @return the value of j_identify.certnum
     *
     * @mbggenerated
     */
    public String getCertnum() {
        return certnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_identify.certnum
     *
     * @param certnum the value for j_identify.certnum
     *
     * @mbggenerated
     */
    public void setCertnum(String certnum) {
        this.certnum = certnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_identify.sessions
     *
     * @return the value of j_identify.sessions
     *
     * @mbggenerated
     */
    public Integer getSessions() {
        return sessions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_identify.sessions
     *
     * @param sessions the value for j_identify.sessions
     *
     * @mbggenerated
     */
    public void setSessions(Integer sessions) {
        this.sessions = sessions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_identify.positions
     *
     * @return the value of j_identify.positions
     *
     * @mbggenerated
     */
    public String getPositions() {
        return positions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_identify.positions
     *
     * @param positions the value for j_identify.positions
     *
     * @mbggenerated
     */
    public void setPositions(String positions) {
        this.positions = positions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_identify.descriptions
     *
     * @return the value of j_identify.descriptions
     *
     * @mbggenerated
     */
    public String getDescriptions() {
        return descriptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_identify.descriptions
     *
     * @param descriptions the value for j_identify.descriptions
     *
     * @mbggenerated
     */
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }
}