package com.jplus.model;

import java.io.Serializable;
import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;

/**
 * 此类由MySQLToModel工具自动生成 
 * 备注(数据表的comment字段)：无备注信息
 * 
 * @author Chitry
 * @title Jplus常务公告实体
 * @since 2015-07-22 19:52:51
 */
public class Jnotice implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_jnotice.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_jnotice.notice_title
     *
     * @mbggenerated
     */
    @Autowired
    private User user;
    
    private String noticeTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_jnotice.notice_reltime
     *
     * @mbggenerated
     */
    private Date noticeReltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_jnotice.notice_author_id
     *
     * @mbggenerated
     */
    private Integer noticeAuthorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_jnotice.notice_content
     *
     * @mbggenerated
     */
    private String noticeContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_jnotice.id
     *
     * @return the value of j_jnotice.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_jnotice.id
     *
     * @param id the value for j_jnotice.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_jnotice.notice_title
     *
     * @return the value of j_jnotice.notice_title
     *
     * @mbggenerated
     */
    public String getNoticeTitle() {
        return noticeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_jnotice.notice_title
     *
     * @param noticeTitle the value for j_jnotice.notice_title
     *
     * @mbggenerated
     */
    public void setNoticeTitle(String noticeTitle) {
        this.noticeTitle = noticeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_jnotice.notice_reltime
     *
     * @return the value of j_jnotice.notice_reltime
     *
     * @mbggenerated
     */
    public Date getNoticeReltime() {
        return noticeReltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_jnotice.notice_reltime
     *
     * @param noticeReltime the value for j_jnotice.notice_reltime
     *
     * @mbggenerated
     */
    public void setNoticeReltime(Date noticeReltime) {
        this.noticeReltime = noticeReltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_jnotice.notice_author_id
     *
     * @return the value of j_jnotice.notice_author_id
     *
     * @mbggenerated
     */
    public Integer getNoticeAuthorId() {
        return noticeAuthorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_jnotice.notice_author_id
     *
     * @param noticeAuthorId the value for j_jnotice.notice_author_id
     *
     * @mbggenerated
     */
    public void setNoticeAuthorId(Integer noticeAuthorId) {
        this.noticeAuthorId = noticeAuthorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_jnotice.notice_content
     *
     * @return the value of j_jnotice.notice_content
     *
     * @mbggenerated
     */
    public String getNoticeContent() {
        return noticeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_jnotice.notice_content
     *
     * @param noticeContent the value for j_jnotice.notice_content
     *
     * @mbggenerated
     */
    public void setNoticeContent(String noticeContent) {
        this.noticeContent = noticeContent;
    }

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
    
}