package com.jplus.model;

import java.io.Serializable;
import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;


/**
 * 此类由MySQLToModel工具自动生成 
 * 备注(数据表的comment字段)：无备注信息
 * 
 * @author Chitry
 * @title Jplus常务任务大厅任务实体
 * @since 2015-07-22 19:52:51
 */
public class Jtask implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_jtask.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_jtask.task_title
     *
     * @mbggenerated
     */
    @Autowired
    private User user;
    private String taskTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_jtask.task_description
     *
     * @mbggenerated
     */
    private String taskDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_jtask.task_reltime
     *
     * @mbggenerated
     */
    private Date taskReltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_jtask.task_author_id
     *
     * @mbggenerated
     */
    private Integer taskAuthorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_jtask.task_content
     *
     * @mbggenerated
     */
    private String taskContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_jtask.id
     *
     * @return the value of j_jtask.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_jtask.id
     *
     * @param id the value for j_jtask.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_jtask.task_title
     *
     * @return the value of j_jtask.task_title
     *
     * @mbggenerated
     */
    public String getTaskTitle() {
        return taskTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_jtask.task_title
     *
     * @param taskTitle the value for j_jtask.task_title
     *
     * @mbggenerated
     */
    public void setTaskTitle(String taskTitle) {
        this.taskTitle = taskTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_jtask.task_description
     *
     * @return the value of j_jtask.task_description
     *
     * @mbggenerated
     */
    public String getTaskDescription() {
        return taskDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_jtask.task_description
     *
     * @param taskDescription the value for j_jtask.task_description
     *
     * @mbggenerated
     */
    public void setTaskDescription(String taskDescription) {
        this.taskDescription = taskDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_jtask.task_reltime
     *
     * @return the value of j_jtask.task_reltime
     *
     * @mbggenerated
     */
    public Date getTaskReltime() {
        return taskReltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_jtask.task_reltime
     *
     * @param taskReltime the value for j_jtask.task_reltime
     *
     * @mbggenerated
     */
    public void setTaskReltime(Date taskReltime) {
        this.taskReltime = taskReltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_jtask.task_author_id
     *
     * @return the value of j_jtask.task_author_id
     *
     * @mbggenerated
     */
    public Integer getTaskAuthorId() {
        return taskAuthorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_jtask.task_author_id
     *
     * @param taskAuthorId the value for j_jtask.task_author_id
     *
     * @mbggenerated
     */
    public void setTaskAuthorId(Integer taskAuthorId) {
        this.taskAuthorId = taskAuthorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_jtask.task_content
     *
     * @return the value of j_jtask.task_content
     *
     * @mbggenerated
     */
    public String getTaskContent() {
        return taskContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_jtask.task_content
     *
     * @param taskContent the value for j_jtask.task_content
     *
     * @mbggenerated
     */
    public void setTaskContent(String taskContent) {
        this.taskContent = taskContent;
    }

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
    
}