package com.jplus.model;

import java.util.Date;

public class LiuYan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_liuyan.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_liuyan.commenduser
     *
     * @mbggenerated
     */
    private String commenduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_liuyan.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_liuyan.commendtime
     *
     * @mbggenerated
     */
    private Date commendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_liuyan.commendresponse
     *
     * @mbggenerated
     */
    private String commendresponse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_liuyan.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_liuyan.Id
     *
     * @return the value of j_liuyan.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_liuyan.Id
     *
     * @param id the value for j_liuyan.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_liuyan.commenduser
     *
     * @return the value of j_liuyan.commenduser
     *
     * @mbggenerated
     */
    public String getCommenduser() {
        return commenduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_liuyan.commenduser
     *
     * @param commenduser the value for j_liuyan.commenduser
     *
     * @mbggenerated
     */
    public void setCommenduser(String commenduser) {
        this.commenduser = commenduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_liuyan.content
     *
     * @return the value of j_liuyan.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_liuyan.content
     *
     * @param content the value for j_liuyan.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_liuyan.commendtime
     *
     * @return the value of j_liuyan.commendtime
     *
     * @mbggenerated
     */
    public Date getCommendtime() {
        return commendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_liuyan.commendtime
     *
     * @param commendtime the value for j_liuyan.commendtime
     *
     * @mbggenerated
     */
    public void setCommendtime(Date commendtime) {
        this.commendtime = commendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_liuyan.commendresponse
     *
     * @return the value of j_liuyan.commendresponse
     *
     * @mbggenerated
     */
    public String getCommendresponse() {
        return commendresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_liuyan.commendresponse
     *
     * @param commendresponse the value for j_liuyan.commendresponse
     *
     * @mbggenerated
     */
    public void setCommendresponse(String commendresponse) {
        this.commendresponse = commendresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_liuyan.description
     *
     * @return the value of j_liuyan.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_liuyan.description
     *
     * @param description the value for j_liuyan.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }
}