package com.jplus.model;

import java.io.Serializable;

/**
 * 此类由MySQLToModel工具自动生成 
 * 备注(数据表的comment字段)：无备注信息
 * 
 * @author Chitry
 * @title 网站静态图片实体
 * @since 2015-07-22 19:52:51
 */
public class NetPurl implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_netpurl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_netpurl.np_title
     *
     * @mbggenerated
     */
    private String npTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_netpurl.np_url
     *
     * @mbggenerated
     */
    private String npUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_netpurl.np_descriptions
     *
     * @mbggenerated
     */
    private String npDescriptions;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_netpurl.id
     *
     * @return the value of j_netpurl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_netpurl.id
     *
     * @param id the value for j_netpurl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_netpurl.np_title
     *
     * @return the value of j_netpurl.np_title
     *
     * @mbggenerated
     */
    public String getNpTitle() {
        return npTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_netpurl.np_title
     *
     * @param npTitle the value for j_netpurl.np_title
     *
     * @mbggenerated
     */
    public void setNpTitle(String npTitle) {
        this.npTitle = npTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_netpurl.np_url
     *
     * @return the value of j_netpurl.np_url
     *
     * @mbggenerated
     */
    public String getNpUrl() {
        return npUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_netpurl.np_url
     *
     * @param npUrl the value for j_netpurl.np_url
     *
     * @mbggenerated
     */
    public void setNpUrl(String npUrl) {
        this.npUrl = npUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_netpurl.np_descriptions
     *
     * @return the value of j_netpurl.np_descriptions
     *
     * @mbggenerated
     */
    public String getNpDescriptions() {
        return npDescriptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_netpurl.np_descriptions
     *
     * @param npDescriptions the value for j_netpurl.np_descriptions
     *
     * @mbggenerated
     */
    public void setNpDescriptions(String npDescriptions) {
        this.npDescriptions = npDescriptions;
    }
}