package com.jplus.model;

import java.io.Serializable;
import java.util.Date;


/**
 * 此类由MySQLToModel工具自动生成 
 * 备注(数据表的comment字段)：无备注信息
 * 
 * @author Chitry
 * @title 招聘信息实体
 * @since 2015-07-22 19:52:51
 */
public class Recruit implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_recruit.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_recruit.re_title
     *
     * @mbggenerated
     */
    private String reTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_recruit.re_description
     *
     * @mbggenerated
     */
    private String reDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_recruit.re_provide
     *
     * @mbggenerated
     */
    private String reProvide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_recruit.re_date
     *
     * @mbggenerated
     */
    private Date reDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_recruit.re_enddate
     *
     * @mbggenerated
     */
    private Date reEnddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_recruit.re_author_id
     *
     * @mbggenerated
     */
    private Integer reAuthorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_recruit.re_told
     *
     * @mbggenerated
     */
    private String reTold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_recruit.re_prize
     *
     * @mbggenerated
     */
    private Integer rePrize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_recruit.re_content
     *
     * @mbggenerated
     */
    private String reContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_recruit.id
     *
     * @return the value of j_recruit.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_recruit.id
     *
     * @param id the value for j_recruit.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_recruit.re_title
     *
     * @return the value of j_recruit.re_title
     *
     * @mbggenerated
     */
    public String getReTitle() {
        return reTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_recruit.re_title
     *
     * @param reTitle the value for j_recruit.re_title
     *
     * @mbggenerated
     */
    public void setReTitle(String reTitle) {
        this.reTitle = reTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_recruit.re_description
     *
     * @return the value of j_recruit.re_description
     *
     * @mbggenerated
     */
    public String getReDescription() {
        return reDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_recruit.re_description
     *
     * @param reDescription the value for j_recruit.re_description
     *
     * @mbggenerated
     */
    public void setReDescription(String reDescription) {
        this.reDescription = reDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_recruit.re_provide
     *
     * @return the value of j_recruit.re_provide
     *
     * @mbggenerated
     */
    public String getReProvide() {
        return reProvide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_recruit.re_provide
     *
     * @param reProvide the value for j_recruit.re_provide
     *
     * @mbggenerated
     */
    public void setReProvide(String reProvide) {
        this.reProvide = reProvide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_recruit.re_date
     *
     * @return the value of j_recruit.re_date
     *
     * @mbggenerated
     */
    public Date getReDate() {
        return reDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_recruit.re_date
     *
     * @param reDate the value for j_recruit.re_date
     *
     * @mbggenerated
     */
    public void setReDate(Date reDate) {
        this.reDate = reDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_recruit.re_enddate
     *
     * @return the value of j_recruit.re_enddate
     *
     * @mbggenerated
     */
    public Date getReEnddate() {
        return reEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_recruit.re_enddate
     *
     * @param reEnddate the value for j_recruit.re_enddate
     *
     * @mbggenerated
     */
    public void setReEnddate(Date reEnddate) {
        this.reEnddate = reEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_recruit.re_author_id
     *
     * @return the value of j_recruit.re_author_id
     *
     * @mbggenerated
     */
    public Integer getReAuthorId() {
        return reAuthorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_recruit.re_author_id
     *
     * @param reAuthorId the value for j_recruit.re_author_id
     *
     * @mbggenerated
     */
    public void setReAuthorId(Integer reAuthorId) {
        this.reAuthorId = reAuthorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_recruit.re_told
     *
     * @return the value of j_recruit.re_told
     *
     * @mbggenerated
     */
    public String getReTold() {
        return reTold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_recruit.re_told
     *
     * @param reTold the value for j_recruit.re_told
     *
     * @mbggenerated
     */
    public void setReTold(String reTold) {
        this.reTold = reTold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_recruit.re_prize
     *
     * @return the value of j_recruit.re_prize
     *
     * @mbggenerated
     */
    public Integer getRePrize() {
        return rePrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_recruit.re_prize
     *
     * @param rePrize the value for j_recruit.re_prize
     *
     * @mbggenerated
     */
    public void setRePrize(Integer rePrize) {
        this.rePrize = rePrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_recruit.re_content
     *
     * @return the value of j_recruit.re_content
     *
     * @mbggenerated
     */
    public String getReContent() {
        return reContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_recruit.re_content
     *
     * @param reContent the value for j_recruit.re_content
     *
     * @mbggenerated
     */
    public void setReContent(String reContent) {
        this.reContent = reContent;
    }
}