package com.jplus.model;

import java.io.Serializable;
import java.util.Date;

/**
 * 此类由MySQLToModel工具自动生成 
 * 备注(数据表的comment字段)：无备注信息
 * 
 * @author Chitry
 * @title 资源实体
 * @since 2015-07-22 19:52:51
 */
public class Res implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.id
     *
     * @mbggenerated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userzz
     *
     * @mbggenerated
     */
    
    private String userzz;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resclassds
     *
     * @mbggenerated
     */
    
    private String resclassds;
    public String getResclassds() {
		return resclassds;
	}

	public void setResclassds(String resclassds) {
		this.resclassds = resclassds;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.resname
     *
     * @mbggenerated
     */
    

    private String resname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.resdescription
     *
     * @mbggenerated
     */
    private String resdescription;

    public String getUserzz() {
		return userzz;
	}

	public void setUserzz(String userzz) {
		this.userzz = userzz;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.res_bdypath
     *
     * @mbggenerated
     */
    private String resBdypath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.res_bdypassword
     *
     * @mbggenerated
     */
    private String resBdypassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.res_360path
     *
     * @mbggenerated
     */
    private String res360path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.res_360password
     *
     * @mbggenerated
     */
    private String res360password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.res_locationpath
     *
     * @mbggenerated
     */
    private String resLocationpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.downloadnum
     *
     * @mbggenerated
     */
    private Integer downloadnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.downloadscore
     *
     * @mbggenerated
     */
    private Integer downloadscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.resdate
     *
     * @mbggenerated
     */
    private Date resdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.resstate
     *
     * @mbggenerated
     */
    private Integer resstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.resdiscuss
     *
     * @mbggenerated
     */
    private Integer resdiscuss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.resclass_id
     *
     * @mbggenerated
     */
    private Integer resclassId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_res.id
     *
     * @return the value of j_res.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_res.id
     *
     * @param id the value for j_res.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_res.resname
     *
     * @return the value of j_res.resname
     *
     * @mbggenerated
     */
    public String getResname() {
        return resname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_res.resname
     *
     * @param resname the value for j_res.resname
     *
     * @mbggenerated
     */
    public void setResname(String resname) {
        this.resname = resname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_res.resdescription
     *
     * @return the value of j_res.resdescription
     *
     * @mbggenerated
     */
    public String getResdescription() {
        return resdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_res.resdescription
     *
     * @param resdescription the value for j_res.resdescription
     *
     * @mbggenerated
     */
    public void setResdescription(String resdescription) {
        this.resdescription = resdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_res.res_bdypath
     *
     * @return the value of j_res.res_bdypath
     *
     * @mbggenerated
     */
    public String getResBdypath() {
        return resBdypath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_res.res_bdypath
     *
     * @param resBdypath the value for j_res.res_bdypath
     *
     * @mbggenerated
     */
    public void setResBdypath(String resBdypath) {
        this.resBdypath = resBdypath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_res.res_bdypassword
     *
     * @return the value of j_res.res_bdypassword
     *
     * @mbggenerated
     */
    public String getResBdypassword() {
        return resBdypassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_res.res_bdypassword
     *
     * @param resBdypassword the value for j_res.res_bdypassword
     *
     * @mbggenerated
     */
    public void setResBdypassword(String resBdypassword) {
        this.resBdypassword = resBdypassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_res.res_360path
     *
     * @return the value of j_res.res_360path
     *
     * @mbggenerated
     */
    public String getRes360path() {
        return res360path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_res.res_360path
     *
     * @param res360path the value for j_res.res_360path
     *
     * @mbggenerated
     */
    public void setRes360path(String res360path) {
        this.res360path = res360path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_res.res_360password
     *
     * @return the value of j_res.res_360password
     *
     * @mbggenerated
     */
    public String getRes360password() {
        return res360password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_res.res_360password
     *
     * @param res360password the value for j_res.res_360password
     *
     * @mbggenerated
     */
    public void setRes360password(String res360password) {
        this.res360password = res360password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_res.res_locationpath
     *
     * @return the value of j_res.res_locationpath
     *
     * @mbggenerated
     */
    public String getResLocationpath() {
        return resLocationpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_res.res_locationpath
     *
     * @param resLocationpath the value for j_res.res_locationpath
     *
     * @mbggenerated
     */
    public void setResLocationpath(String resLocationpath) {
        this.resLocationpath = resLocationpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_res.downloadnum
     *
     * @return the value of j_res.downloadnum
     *
     * @mbggenerated
     */
    public Integer getDownloadnum() {
        return downloadnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_res.downloadnum
     *
     * @param downloadnum the value for j_res.downloadnum
     *
     * @mbggenerated
     */
    public void setDownloadnum(Integer downloadnum) {
        this.downloadnum = downloadnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_res.downloadscore
     *
     * @return the value of j_res.downloadscore
     *
     * @mbggenerated
     */
    public Integer getDownloadscore() {
        return downloadscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_res.downloadscore
     *
     * @param downloadscore the value for j_res.downloadscore
     *
     * @mbggenerated
     */
    public void setDownloadscore(Integer downloadscore) {
        this.downloadscore = downloadscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_res.resdate
     *
     * @return the value of j_res.resdate
     *
     * @mbggenerated
     */
    public Date getResdate() {
        return resdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_res.resdate
     *
     * @param resdate the value for j_res.resdate
     *
     * @mbggenerated
     */
    public void setResdate(Date resdate) {
        this.resdate = resdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_res.resstate
     *
     * @return the value of j_res.resstate
     *
     * @mbggenerated
     */
    public Integer getResstate() {
        return resstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_res.resstate
     *
     * @param resstate the value for j_res.resstate
     *
     * @mbggenerated
     */
    public void setResstate(Integer resstate) {
        this.resstate = resstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_res.resdiscuss
     *
     * @return the value of j_res.resdiscuss
     *
     * @mbggenerated
     */
    public Integer getResdiscuss() {
        return resdiscuss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_res.resdiscuss
     *
     * @param resdiscuss the value for j_res.resdiscuss
     *
     * @mbggenerated
     */
    public void setResdiscuss(Integer resdiscuss) {
        this.resdiscuss = resdiscuss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_res.resclass_id
     *
     * @return the value of j_res.resclass_id
     *
     * @mbggenerated
     */
    public Integer getResclassId() {
        return resclassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_res.resclass_id
     *
     * @param resclassId the value for j_res.resclass_id
     *
     * @mbggenerated
     */
    public void setResclassId(Integer resclassId) {
        this.resclassId = resclassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_res.user_id
     *
     * @return the value of j_res.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_res.user_id
     *
     * @param userId the value for j_res.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}