package com.jplus.model;

import java.io.Serializable;

/**
 * 此类由MySQLToModel工具自动生成 
 * 备注(数据表的comment字段)：无备注信息
 * 
 * @author Chitry
 * @title 资源类实体
 * @since 2015-07-22 19:52:51
 */
public class ResClass implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_resclass.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_resclass.resname
     *
     * @mbggenerated
     */
    private String resname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_resclass.isbdydown
     *
     * @mbggenerated
     */
    private Integer isbdydown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_resclass.is360down
     *
     * @mbggenerated
     */
    private Integer is360down;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_resclass.islocationdown
     *
     * @mbggenerated
     */
    private Integer islocationdown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_resclass.resdescription
     *
     * @mbggenerated
     */
    private String resdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_resclass.respurl
     *
     * @mbggenerated
     */
    private String respurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_resclass.id
     *
     * @return the value of j_resclass.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_resclass.id
     *
     * @param id the value for j_resclass.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_resclass.resname
     *
     * @return the value of j_resclass.resname
     *
     * @mbggenerated
     */
    public String getResname() {
        return resname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_resclass.resname
     *
     * @param resname the value for j_resclass.resname
     *
     * @mbggenerated
     */
    public void setResname(String resname) {
        this.resname = resname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_resclass.isbdydown
     *
     * @return the value of j_resclass.isbdydown
     *
     * @mbggenerated
     */
    public Integer getIsbdydown() {
        return isbdydown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_resclass.isbdydown
     *
     * @param isbdydown the value for j_resclass.isbdydown
     *
     * @mbggenerated
     */
    public void setIsbdydown(Integer isbdydown) {
        this.isbdydown = isbdydown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_resclass.is360down
     *
     * @return the value of j_resclass.is360down
     *
     * @mbggenerated
     */
    public Integer getIs360down() {
        return is360down;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_resclass.is360down
     *
     * @param is360down the value for j_resclass.is360down
     *
     * @mbggenerated
     */
    public void setIs360down(Integer is360down) {
        this.is360down = is360down;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_resclass.islocationdown
     *
     * @return the value of j_resclass.islocationdown
     *
     * @mbggenerated
     */
    public Integer getIslocationdown() {
        return islocationdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_resclass.islocationdown
     *
     * @param islocationdown the value for j_resclass.islocationdown
     *
     * @mbggenerated
     */
    public void setIslocationdown(Integer islocationdown) {
        this.islocationdown = islocationdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_resclass.resdescription
     *
     * @return the value of j_resclass.resdescription
     *
     * @mbggenerated
     */
    public String getResdescription() {
        return resdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_resclass.resdescription
     *
     * @param resdescription the value for j_resclass.resdescription
     *
     * @mbggenerated
     */
    public void setResdescription(String resdescription) {
        this.resdescription = resdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_resclass.respurl
     *
     * @return the value of j_resclass.respurl
     *
     * @mbggenerated
     */
    public String getRespurl() {
        return respurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_resclass.respurl
     *
     * @param respurl the value for j_resclass.respurl
     *
     * @mbggenerated
     */
    public void setRespurl(String respurl) {
        this.respurl = respurl;
    }
}