package com.jplus.model;

import java.io.Serializable;


/**
 * 此类由MySQLToModel工具自动生成 
 * 备注(数据表的comment字段)：无备注信息
 * 
 * @author Chitry
 * @title 工具官方推荐信息实体
 * @since 2015-07-22 19:52:51
 */
public class ToolOfficeRecommend implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_toolofficerecommend.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_toolofficerecommend.tor_name
     *
     * @mbggenerated
     */
    private String torName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_toolofficerecommend.tor_title
     *
     * @mbggenerated
     */
    private String torTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_toolofficerecommend.tor_url
     *
     * @mbggenerated
     */
    private String torUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_toolofficerecommend.tor_purl
     *
     * @mbggenerated
     */
    private String torPurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_toolofficerecommend.tor_descriptions
     *
     * @mbggenerated
     */
    private String torDescriptions;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_toolofficerecommend.id
     *
     * @return the value of j_toolofficerecommend.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_toolofficerecommend.id
     *
     * @param id the value for j_toolofficerecommend.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_toolofficerecommend.tor_name
     *
     * @return the value of j_toolofficerecommend.tor_name
     *
     * @mbggenerated
     */
    public String getTorName() {
        return torName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_toolofficerecommend.tor_name
     *
     * @param torName the value for j_toolofficerecommend.tor_name
     *
     * @mbggenerated
     */
    public void setTorName(String torName) {
        this.torName = torName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_toolofficerecommend.tor_title
     *
     * @return the value of j_toolofficerecommend.tor_title
     *
     * @mbggenerated
     */
    public String getTorTitle() {
        return torTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_toolofficerecommend.tor_title
     *
     * @param torTitle the value for j_toolofficerecommend.tor_title
     *
     * @mbggenerated
     */
    public void setTorTitle(String torTitle) {
        this.torTitle = torTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_toolofficerecommend.tor_url
     *
     * @return the value of j_toolofficerecommend.tor_url
     *
     * @mbggenerated
     */
    public String getTorUrl() {
        return torUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_toolofficerecommend.tor_url
     *
     * @param torUrl the value for j_toolofficerecommend.tor_url
     *
     * @mbggenerated
     */
    public void setTorUrl(String torUrl) {
        this.torUrl = torUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_toolofficerecommend.tor_purl
     *
     * @return the value of j_toolofficerecommend.tor_purl
     *
     * @mbggenerated
     */
    public String getTorPurl() {
        return torPurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_toolofficerecommend.tor_purl
     *
     * @param torPurl the value for j_toolofficerecommend.tor_purl
     *
     * @mbggenerated
     */
    public void setTorPurl(String torPurl) {
        this.torPurl = torPurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_toolofficerecommend.tor_descriptions
     *
     * @return the value of j_toolofficerecommend.tor_descriptions
     *
     * @mbggenerated
     */
    public String getTorDescriptions() {
        return torDescriptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_toolofficerecommend.tor_descriptions
     *
     * @param torDescriptions the value for j_toolofficerecommend.tor_descriptions
     *
     * @mbggenerated
     */
    public void setTorDescriptions(String torDescriptions) {
        this.torDescriptions = torDescriptions;
    }
}