package com.jplus.model;

import java.io.Serializable;
import java.util.Date;

/**
 * 此类由MySQLToModel工具自动生成 
 * 备注(数据表的comment字段)：无备注信息
 * 
 * @author Chitry
 * @title 用户信箱实体
 * @since 2015-07-22 19:52:51
 */
public class UserMsg implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_usermsg.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_usermsg.msgcontent
     *
     * @mbggenerated
     */
    private String msgcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_usermsg.readsign
     *
     * @mbggenerated
     */
    private Integer readsign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_usermsg.gettime
     *
     * @mbggenerated
     */
    private Date gettime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_usermsg.sendauthor
     *
     * @mbggenerated
     */
    private String sendauthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_usermsg.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_usermsg.id
     *
     * @return the value of j_usermsg.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_usermsg.id
     *
     * @param id the value for j_usermsg.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_usermsg.msgcontent
     *
     * @return the value of j_usermsg.msgcontent
     *
     * @mbggenerated
     */
    public String getMsgcontent() {
        return msgcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_usermsg.msgcontent
     *
     * @param msgcontent the value for j_usermsg.msgcontent
     *
     * @mbggenerated
     */
    public void setMsgcontent(String msgcontent) {
        this.msgcontent = msgcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_usermsg.readsign
     *
     * @return the value of j_usermsg.readsign
     *
     * @mbggenerated
     */
    public Integer getReadsign() {
        return readsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_usermsg.readsign
     *
     * @param readsign the value for j_usermsg.readsign
     *
     * @mbggenerated
     */
    public void setReadsign(Integer readsign) {
        this.readsign = readsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_usermsg.gettime
     *
     * @return the value of j_usermsg.gettime
     *
     * @mbggenerated
     */
    public Date getGettime() {
        return gettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_usermsg.gettime
     *
     * @param gettime the value for j_usermsg.gettime
     *
     * @mbggenerated
     */
    public void setGettime(Date gettime) {
        this.gettime = gettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_usermsg.sendauthor
     *
     * @return the value of j_usermsg.sendauthor
     *
     * @mbggenerated
     */
    public String getSendauthor() {
        return sendauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_usermsg.sendauthor
     *
     * @param sendauthor the value for j_usermsg.sendauthor
     *
     * @mbggenerated
     */
    public void setSendauthor(String sendauthor) {
        this.sendauthor = sendauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_usermsg.user_id
     *
     * @return the value of j_usermsg.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_usermsg.user_id
     *
     * @param userId the value for j_usermsg.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
	
	  //增添的部分
    private String datetimeString;

	public String getDatetimeString() {
		return datetimeString;
	}

	public void setDatetimeString(String datetimeString) {
		this.datetimeString = datetimeString;
	}
}