package com.jplus.model;

import java.io.Serializable;
//fly 2015/8/1
//为了实现赞的功能临时加的一个数据表j_Zan
public class Zan implements Serializable {
	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.id
     *
     * @mbggenerated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_res.id
     *
     * @mbggenerated
     */
    private Integer userid;
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getUserid() {
		return userid;
	}
	public void setUserid(Integer userid) {
		this.userid = userid;
	}
}
